import SwiftUI
import UIKit

// 4 tabs: Setup (model + repo + idle calibration),
//         Run (per-cell N-problem benchmark),
//         Sustained (5-min thermal probe),
//         Results (list export of jsonls in Documents).
struct ContentView: View {
    @StateObject private var model = ModelLoader()
    @StateObject private var thermal = ThermalMonitor()
    @StateObject private var battery = BatteryMonitor()

    @StateObject private var benchmark: Benchmark
    @StateObject private var sustained: SustainedProbe

    @State private var promptStore: PromptStore?
    @State private var promptError: String?

    init() {
        let m = ModelLoader()
        let th = ThermalMonitor()
        let bt = BatteryMonitor()
        _model = StateObject(wrappedValue: m)
        _thermal = StateObject(wrappedValue: th)
        _battery = StateObject(wrappedValue: bt)
        _benchmark = StateObject(wrappedValue: Benchmark(model: m, thermal: th, battery: bt))
        _sustained = StateObject(wrappedValue: SustainedProbe(model: m, thermal: th, battery: bt))
    }

    var body: some View {
        TabView {
            SetupTab(model: model, battery: battery, store: $promptStore, storeError: $promptError)
                .tabItem { Label("Setup", systemImage: "gearshape") }
            RunTab(benchmark: benchmark, store: $promptStore, model: model, thermal: thermal, battery: battery)
                .tabItem { Label("Run", systemImage: "play.fill") }
            SustainedTab(probe: sustained, store: $promptStore, model: model, thermal: thermal)
                .tabItem { Label("Sustained", systemImage: "flame") }
            ResultsTab()
                .tabItem { Label("Results", systemImage: "doc.text") }
        }
        .onAppear { tryLoadPrompts() }
    }

    private func tryLoadPrompts() {
        do {
            promptStore = try PromptStore.loadFromBundle()
            promptError = nil
        } catch {
            promptError = "\(error)"
        }
    }
}

private struct SetupTab: View {
    @ObservedObject var model: ModelLoader
    @ObservedObject var battery: BatteryMonitor
    @Binding var store: PromptStore?
    @Binding var storeError: String?

    @State private var repoIDDraft: String = ""
    @State private var calibrating = false
    @State private var idleRate: Double?

    var body: some View {
        NavigationStack {
            Form {
                Section("Model") {
                    TextField("HF repo (e.g. mlx-community/gemma-4-E2B-it-4bit-mlx)",
                              text: $repoIDDraft)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                    HStack {
                        Button("Save & Load") {
                            model.saveRepoID(repoIDDraft.isEmpty ? model.repoID : repoIDDraft)
                            Task { await model.load() }
                        }
                        Spacer()
                        modelStatusView
                    }
                }
                Section("Prompts.jsonl (bundled)") {
                    if let store = store {
                        Text("\(store.rows.count) prompt rows loaded")
                    } else if let err = storeError {
                        Text(err).foregroundStyle(.red).font(.caption)
                    }
                    Text("Generated by `python experiments/path1_phone_mac.py --emit-prompts` and copied into the iOS bundle. The Mac and iPhone runs share these byte-equivalent prompts (plan section 5).").font(.caption).foregroundStyle(.secondary)
                }
                Section("Idle baseline (sanity check 6)") {
                    Text("Battery: \(String(format: "%.1f", battery.currentPercent()))% · \(battery.stateName)")
                    if let r = idleRate {
                        Text("Idle drain: \(String(format: "%.4f", r * 60))%/min").font(.caption)
                    }
                    Button(calibrating ? "Calibrating (5 min)..." : "Calibrate idle baseline (5 min)") {
                        Task {
                            calibrating = true
                            idleRate = try? await battery.calibrateIdleBaseline(durationSeconds: 300)
                            calibrating = false
                        }
                    }.disabled(calibrating)
                }
                Section("Run conditions checklist") {
                    Text("[plan section Run conditions]").font(.caption).foregroundStyle(.secondary)
                    Text("• Airplane mode: ON")
                    Text("• Brightness: 50%")
                    Text("• Background app refresh: OFF")
                    Text("• Idle timer: app disables it automatically")
                    Text("• Case: document presence/absence in run notes")
                }
            }
            .navigationTitle("Path1Bench")
            .onAppear { repoIDDraft = model.repoID }
        }
    }

    private var modelStatusView: some View {
        switch model.state {
        case .idle: return AnyView(Text("idle").foregroundStyle(.secondary))
        case .downloading(let p):
            return AnyView(Text(String(format: "%.0f%%", p * 100)).font(.caption.monospacedDigit()))
        case .loading: return AnyView(Text("loading"))
        case .ready: return AnyView(Text("ready").foregroundStyle(.green))
        case .failed(let m): return AnyView(Text(m).foregroundStyle(.red).font(.caption))
        }
    }
}

private struct RunTab: View {
    @ObservedObject var benchmark: Benchmark
    @Binding var store: PromptStore?
    @ObservedObject var model: ModelLoader
    @ObservedObject var thermal: ThermalMonitor
    @ObservedObject var battery: BatteryMonitor

    @State private var n: Int = 50
    @State private var selectedCell: Benchmark.CellID = .c2

    var body: some View {
        NavigationStack {
            Form {
                Section("Cell") {
                    Picker("Cell", selection: $selectedCell) {
                        ForEach(Benchmark.CellID.allCases) { c in
                            Text(c.rawValue).tag(c)
                        }
                    }.pickerStyle(.segmented)
                    Stepper("n = \(n)", value: $n, in: 1...50)
                }
                Section("Run") {
                    Button("Run \(selectedCell.rawValue) on \(n) problems") {
                        guard let store = store else { return }
                        Task { await benchmark.runCell(selectedCell, n: n, store: store) }
                    }
                    .disabled(model.state != .ready || benchmark.isRunning || store == nil)
                    if benchmark.isRunning {
                        ProgressView(value: Double(benchmark.done), total: Double(max(1, benchmark.total)))
                        Text(benchmark.status).font(.caption)
                    } else if !benchmark.status.isEmpty {
                        Text(benchmark.status).font(.caption).foregroundStyle(.secondary)
                    }
                }
                Section("Live") {
                    Text("Battery: \(String(format: "%.1f", battery.currentPercent()))%")
                    Text("Thermal: \(ThermalMonitor.name(of: thermal.current))")
                    if let r = benchmark.lastResult {
                        Text("idx=\(r.idx) wall=\(String(format: "%.2f", r.wallclock_ms/1000))s gen=\(r.gen_tokens) ok=\(r.correct)").font(.caption.monospacedDigit())
                    }
                }
            }
            .navigationTitle("Run")
        }
    }
}

private struct SustainedTab: View {
    @ObservedObject var probe: SustainedProbe
    @Binding var store: PromptStore?
    @ObservedObject var model: ModelLoader
    @ObservedObject var thermal: ThermalMonitor

    @State private var duration: Double = 300
    @State private var cell: Benchmark.CellID = .c2

    var body: some View {
        NavigationStack {
            Form {
                Section("Cell") {
                    Picker("Cell", selection: $cell) {
                        ForEach(Benchmark.CellID.allCases) { c in
                            Text(c.rawValue).tag(c)
                        }
                    }.pickerStyle(.segmented)
                }
                Section("Probe") {
                    Stepper("Duration: \(Int(duration))s",
                            value: $duration, in: 60...900, step: 30)
                    Button("Start sustained probe") {
                        guard let store = store else { return }
                        Task { await probe.run(cell: cell, durationSeconds: duration, store: store) }
                    }.disabled(model.state != .ready || probe.isRunning || store == nil)
                }
                Section("Live") {
                    Text("Elapsed: \(Int(probe.elapsed))s")
                    Text("Tokens/sec: \(String(format: "%.1f", probe.tokensPerSec))")
                    Text("Total tokens: \(probe.totalTokens)")
                    Text("Thermal: \(probe.thermalState)")
                    if !probe.status.isEmpty {
                        Text(probe.status).font(.caption).foregroundStyle(.secondary)
                    }
                }
            }
            .navigationTitle("Sustained")
        }
    }
}

private struct ResultsTab: View {
    @State private var files: [URL] = []

    var body: some View {
        NavigationStack {
            List(files, id: \.self) { url in
                VStack(alignment: .leading) {
                    Text(url.lastPathComponent).font(.system(.body, design: .monospaced))
                    if let attrs = try? FileManager.default.attributesOfItem(atPath: url.path),
                       let size = attrs[.size] as? Int64 {
                        Text("\(size) bytes").font(.caption).foregroundStyle(.secondary)
                    }
                }
            }
            .refreshable { reload() }
            .onAppear { reload() }
            .navigationTitle("Results")
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Reload") { reload() }
                }
            }
            VStack(alignment: .leading) {
                Text("Files are in this app's Documents directory.").font(.caption)
                Text("Retrieve via Files.app → On My iPhone → Path1Bench, or Xcode → Window → Devices and Simulators → Download Container.").font(.caption).foregroundStyle(.secondary)
            }.padding(.horizontal)
        }
    }

    private func reload() {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
        let cells = docs.appendingPathComponent("cells_phone")
        files = (try? FileManager.default.contentsOfDirectory(at: cells, includingPropertiesForKeys: nil)) ?? []
        files.sort { $0.lastPathComponent < $1.lastPathComponent }
    }
}
